name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  format:
    name: Checks / Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup PHP
        uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # v2
        with:
          php-version: "8.5"
          extensions: curl, json

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Format
        run: composer format:check

  refactor:
    name: Checks / Refactor
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup PHP
        uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # v2
        with:
          php-version: "8.5"
          extensions: curl, json

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Rector
        run: composer refactor:check

  analyze:
    name: Checks / Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup PHP
        uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # v2
        with:
          php-version: "8.5"
          extensions: curl, json

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: PHPStan
        run: composer analyze

  test:
    name: Tests / Unit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup PHP
        uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # v2
        with:
          php-version: "8.5"
          extensions: curl, json

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: PHPUnit
        run: composer test
